---
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: bridge
    environment:
      - TZ=${TIME_ZONE}
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/docker/smarthome/homeassistant/config:/config
    ports:
      - '8123:8123'
    #devices:
    #  - /path/to/device:/path/to/device #optional
    restart: unless-stopped
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    network_mode: bridge
    volumes:
      - /home/docker/smarthome/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    ports:
      - '8124:6052'
    environment:
      #- USERNAME=test
      #- PASSWORD=ChangeMe
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /home/docker/smarthome/zigbe2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - '8125:8080'
    environment:
      - TZ=${TIME_ZONE}
      - PUID=1000
      - PGID=1000
    #devices:
      #Make sure this matched your adapter location
      #- /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00:/dev/ttyACM0
  eclipse-mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
        - /home/docker/smarthome/mosquitto/log:/mosquitto/log
        - /home/docker/smarthome/mosquitto/data:/mosquitto/data
        - /home/docker/smarthome/mosquitto/config:/mosquitto/config
        #- /home/docker/smarthome/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - '1883:1883'
      - '1884:1884'
      - '8883:8883'
      - '8884:8884' 
      - '9001:9001'
    tty: true
    stdin_open: true
    environment:
      - PUID=1000
      - PGID=1000
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - TZ=${TIME_ZONE}
      #- PASSWORD=password #optional
      #- HASHED_PASSWORD= #optional
      #- SUDO_PASSWORD=password #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/docker/smarthome/code-server/config:/config:z
      - /home/docker/smarthome/homeassistant/config:/config/workspace/homeassistant:z
      - /home/docker/smarthome/mosquitto/config:/config/workspace/mosquitto:z
      - /home/docker/smarthome/zigbe2mqtt/data:/config/workspace/zigbe2mqtt:z
    ports:
      - 8126:8443
    restart: unless-stopped
